### ISSUE TITLE
OwnPhotos mobile app, sharing features

### ISSUE THREAD

**Issue by jtagcat** [hooram/ownphotos-backend#109]
Hey, I'm using these features on gphotos (mobile):
 - [x] Upload all photos/videos (done by the nextcloud app)
 - [ ] Delete uploaded media locally
 - [ ] View uploaded and local photos in one place
 - [ ] Sharing:
   - [ ] When sharing uploaded media, download it and then share
   - [ ] If the media is large, offer to create a link to the media instead and then share that
 - [x] Access mobile media from web
Most people actually use gphotos because their mobile storage gets full.

**Comment by guysoft** [comment]
I am not sure what you are talking about - are you writing an app? or connecting it to gphotos which is something else?

**Comment by moeenio** [comment]
I think they are requesting features from Google Photos, to be somehow implemented in ownphotos.

**Comment by jtagcat** [comment]
To my credit, ownphotos claims to be a google photos replacement, that's why I came asking in the first place.

What me and double-digit friends, same-industry persons are looking for is the ability to have a hybrid gallery. The magic thing with google photos is, that on 8GB phones, or even 128GB phones, people run out of space.  
If you've ever demoed files on demand (dropbox, vfs nextcloud) on Windows, you'd get what the hybrid stuff is about. You have one cohesive library, fitting 300GB of photos on any device. I, personally,  don't need that feature, but have seen myself, users in the lower hundreds depending on this by now.

That's what gphotos did — dominated the market, allowing, 'removing the (imminent) need' for something other to be developed. Samsung cloud was a thing, similar to google, they are closing their service fully.

This though, is only a web app, not sure if expanding to a mobile app is in scope or not. @hooram please open if in scope.
