### ISSUE TITLE
Add environment variable to support a password for redis

### ISSUE THREAD

**Issue by halkeye** [hooram/ownphotos-backend#116]
you already have REDIS_HOST, and REDIS_PORT, you just need a REDIS_PASS

https://django-redis-cache.readthedocs.io/en/latest/advanced_configuration.html#location-schemes

I was able to work around it by changing REDIS_HOST=redis to REDIS_HOST=:password@redis which is a little hacky

**Comment by guysoft** [comment]
Pull requests are welcome, not going to implement otherwise.
