### ISSUE TITLE
Lack of SSL (HTTPS) make it completely insecure

### ISSUE THREAD

**Issue by Expro** [hooram/ownphotos-backend#117]
Hi,

Currently, Ownphotos work only via HTTP, thus giving away passwords and transferred content to anyone listening. Considering that it may provide access to a lot of sensitive informations (faces, names, locations in time...) and work as gateway to Nextcloud via provided credentials, giving away access to even more sensitive data, it makes entire projects unusable in anything other than demo envinronments, which is damn shame, as otherwise it is very high quality tool.

Please provide support for HTTPS with custom pair of certificate + private key.

Regards,
Expro

**Comment by StefanAbl** [comment]
Couldn't HTTPS Encryption be achieved using a reverse proxy like nginx. Though I strongly agree it should be using HTTPS and a self sign cert out of the box.

**Comment by guysoft** [comment]
Indeed, use nginx-proxy 
https://github.com/jwilder/nginx-proxy
got that setup here
