### ISSUE TITLE
Project abandoned

### ISSUE THREAD

**Issue by guysoft** [hooram/ownphotos-backend#137]
Hey all,
It seems like @hooram has not responded in months. I have no clue how most of the code works. So I think we should declare that on the main page unless @hooram disagrees.

**Comment by dennorske** [comment]
That is quite sad, if that is the reality. Instead of declaring it anything, we can instead inform that there are no regular updates at the moment. 
The project is such a great idea and cool thing for the self-hosting community, and if this was improved bit by bit in the long run, it could potentially turn out quite big and very usable.

Can someone else with knowledge carry on with a fork of it, or something? I wish I could contribute somehow.

**Comment by guysoft** [comment]
@dennorske I totally agree. But I don't have the scope to take it all on, I would love to help on if there is anyone on board, and there seems to be quite a lot of call of it. Personally I'd crowed fund it to be maintained regularly. But at the moment I only see bug reports piling up, and I thing that announcing it might push people to action.

**Comment by dennorske** [comment]
understand that you can't cope with it alone and that it is a big project. What if someone/you went ahead on r/selfhosted and wrote a little article explaining the situation and that it has big potential - and that help is needed? I bet most users don't know this, and I am fairly sure there are some smart people out there willing to jump on. I'd be happy to contribute by testing and setting up docker-stuff for it, but thats about what I think I can do, besides some python.

**Comment by guysoft** [comment]
I am willing to do that. But it would help if @hooram also backs me on this. So I am giving it a while before writing up something like that. Since he usually took a week or so before his tracks vanished.

**Comment by TKaluza** [comment]
Would be great seeing here some progress! I love the idea!

**Comment by DigitalWarrior** [comment]
I am willing to help. I think with a group effort and mentality and @guysoft coordinating the team OwnPhotos can grow. Time for fresh blood and renewed effort as this project has such potential. Not to diss on @hooram but if he does not have the time or interest.

**Comment by DamonLane** [comment]
I agree, I've been hopefully checking on this project for many months. Given the self hosted version of google photos features, the suggested r/selfhosted announcement could also go on the privacy and de-google subs and other channels to draw in coders and funders. I also hope @hooram at least gives us their blessing if not getting back involved with more support. Does anyone know if any of the forks are already doing this?

**Comment by jab416171** [comment]
I'd also be able to help out, but like @guysoft said it's not a project I can take on entirely by myself.

**Comment by gunzouts** [comment]
Hi guys! I just discovered this fantastic projet and I would also like to help! I will likely start out by fixing some bugs to get to know the project better. Let’s do this 😃

**Comment by AmirSavand** [comment]
Oh god, I wish this issue never existed 😭.

I love to see where this is going, hope the community can keep it **maintained**.

Is there any working **demo** by anyone?

**Comment by Dakunier** [comment]
I found this project a few weeks ago, hope you can maintain it somehow.

Good Luck ;)

**Comment by phantomtypist** [comment]
Hi there everyone!

This project looks really good and the code base is nice.  It's a shame to let it wither away after all the hard work put in by the contributors.

Over time I have come to terms with being a necromammer (necromancer programmer).  Has anyone tried physically contacting @hooram yet outside of Github?

We should try to reach out to Hooram and see if he is still alive.  If we reach him we should discuss transferring the repo.  The last thing you want to do for a project like this is fork it with the same name as it will just cause confusion later down the road.

**Comment by DigitalWarrior** [comment]
Several of us have reached out. Next steps are in progress.

**Comment by phantomtypist** [comment]
I made contact with two of his friends.  They have contacted him.

**Comment by guysoft** [comment]
@phantomtypist Any news?

**Comment by phantomtypist** [comment]
No, but I'll follow up with the two of his friends I made contact with. FWIW his employer on LinkedIn said he didn't work there anymore.
________________________________

**Comment by DigitalWarrior** [comment]
It has been a month and we are not getting anywhere. I have Forked the
repos and invited you as a colab. Renamed to yourphotos. My other thaughts
is a Yourphotos account this way o e person is not in control of the repos,
thaughts?

**Comment by phantomtypist** [comment]
Make it a Github organization and put us under it.  Enforce 2FA auth.

**Comment by DigitalWarrior** [comment]
I will do it tonight in approx 10 hrs. When I get home, unless anyone else speaks up before then with any other idea or has an issue with that direction.

**Comment by phantomtypist** [comment]
See what @guysoft has to say.

My personal thoughts are that, sadly, I guess it will have to come to this.  @hooram doesn't appear to respond to his personal friends and he appears to have separated from his last employer noted on LinkedIn.  If he hasn't passed on, then he certainly has dropped off the face of the digital world.  There seems to be no way to tell if he's doing OK, but I hope he can get past whatever is going on in his life.

**Comment by DigitalWarrior** [comment]
Yes, the latest I could find a digital fingerprint for him was 2 months ago on reddit.  I hope all is well with him.

**Comment by isleshocky77** [comment]
I'm not 100% on board for changing the name of the project. I get where you're saying there can be some issues with a fork without changing the name; however, I personally think there is more confusion with a fork and a different name.

I feel it's better to keep the same name, put it in an organization with multiple contributors, and update the README and description of the project to point out very clearly what is going on, why there is a fork, how to contribute, and how to check for the latest updates.

The insights and network graph should very clear to people how the project was forked and which is the latest and correct project to use.

**Comment by phantomtypist** [comment]
I actually just realized a week or so ago I pre-created the https://github.com/ownphotos organization.

¯\\_(ツ)_/¯

Let's take a vote over the next couple of days.

All in favor of 1) keeping the same project name (to avoid confusion) and 2) fork this repo to the new OwnPhotos Github organization?

@hooram, if you ever get passed whatever is going on in your life you'll be more than welcome to come back to help out with the project under the new org.  Godspeed buddy.

**Comment by yourphotos** [comment]
2. As it will cut down on confusion on the repo. If @hooram comes back of course he is welcome and could point at yourphotos.

**Comment by F1orian** [comment]
I'm voting for option 1.) and for forking this repo to the new ownphotos organization
I think changing the name just causes unnecessary confusion, and I like the name ownphotos better than yourphotos

**Comment by phantomtypist** [comment]
@F1orian this is why I am trying to track down Hooram because forking, let alone renaming, is the worst possible path you can go in situations like this.

**Comment by yourphotos** [comment]
@phantomtypist what is your preferd chat medium?

**Comment by Elektroman2** [comment]
> I'm voting for option 1.) and for forking this repo to the new ownphotos organization
> I think changing the name just causes unnecessary confusion, and I like the name ownphotos better than yourphotos

If me as an outsider, can mention i would recommend a renaming with a trivial name, like Ownphotos_ng (next gen) or Ownphotos2 or Ownphotos_improved or somethong like that.But hopefully the original developer will appear 🙂
Regards, Marcell

**Comment by jab416171** [comment]
I don't think we should rename, but we could do what happened with ownCloud/Nextcloud and call it nextphotos :)

Can you add me as a collaborator to the new org?

**Comment by alorimer** [comment]
It's a real shame that @hooram has abandoned this project which he obviously worked so hard on, but I'm glad to see there's still lots of interest and potential for this to be revived.

I agree with @F1orian and don't think it's worth renaming it. Two concurrent versions of a project definitely should have different names, but that's not the case here - there is really no reason to change the name other than the technical issues of continuing this repository. However, it may be useful to add some identifier to the new repo name to distinguish it from this one, as @Elektroman2 said. I also just like the name "OwnPhotos" and don't see any reason to change it.

**Comment by DamonLane** [comment]
I'd also vote to keep the same name, with clear description of the lineage.

**Comment by TKaluza** [comment]
I'd also vote to keep the same, with clear description of the lineage.

**Comment by dennorske** [comment]
I agree keeping the name and making it clear that it has forked - and
possibly a little note why it was done. I am not familiar with if someone
has write access to the readme or so but everything could just be put
nicely there.

I wish you all good luck with that and I appreciate that there are people
willing to work on the project! Let's just cross our fingers that hooram is
doing alright.

**Comment by guysoft** [comment]
I would vote changing the name. I think parts of the code are going to go though heavy changes and break some compatibility for the project to mature. The name change could help distinguish that. Also there is a license issue. Although it seems not too likely, the name "OwnPhotos" belongs to @hooram , he could come at some point and legitimately claim that its his name and that we can't use it. Possibly not include it in any point in the software. As long as we don't have written permission its his copyright. As much as its a pain and should require coding changes.
BTW "you photos" when searching reidrects to google photos "your photos" page. Not sure its good SEO choice. If we want to promote the FOSS side LibrePhotos seems free. But I am open to any name.
I would love staying with the name, but only if @hooram gives us permission.
Also - ownCloud GmbH might also complain later of if this project becomes wider spread.

**Comment by IamJeffG** [comment]
Given @hooram's silence thus far, I'd suggest to fork and keep the same name -- and if/when he comes back, if he has a problem with our fork sharing a name (my hope is that he'll be thrilled) then we can rename our fork in response.

**Comment by phantomtypist** [comment]
@IamJeffG that's actually the best response I've seen thus far.

I've talked to several people that each want to go their own way.  I think it's fine if this fragments into several forks, along with one keeping the same name in case @hooram comes back.  Some people want to take it in a different direction than others and that's OK.

As for forking with the same name, I think the best path forward for that one is to work on bug fixes, outstanding issues, and already planned new features.  This way it keeps true to where Hooram left off.  After that... just see where it goes.

**Comment by zlavallee** [comment]
Late to the party here, but I would be interested in helping out with some development. Whats the state of the new project repo? Seems like there are a bunch of forks, but I am not sure if any are being actively worked on.

**Comment by guysoft** [comment]
@zlavallee none of the forks to my knowledge have done any code changes. The frontend repo is a mess, no one will touch it.

**Comment by guysoft** [comment]
Actually @lizyeseul has been touching the frontend a little he doesn't speak English or how to work with git AFIK 
see: https://github.com/hooram/ownphotos-frontend/pull/40

**Comment by zlavallee** [comment]
@guysoft Thanks. Can I create a PR to this repo or the front end repo or is this specific repo completely dead?

**Comment by guysoft** [comment]
@zlavallee Make a PR anywhere you see something that can be improved, I can merge it AFAIK

**Comment by karthikiyengar** [comment]
Okay, I'd be keen to contribute. Can someone who has more experience with the project lay out a roadmap? What works, what doesn't, what needs improving and so on?

Also, I see no developments on the fork. Have we agreed to use it? Is there a Gitter or something equivalent where we can discuss the project?

**Comment by guysoft** [comment]
@karthikiyengar There has been no agreement and @hooram who is the only one who had a roadmap will not talk to anyone. So what ever you deicide is the roadmap. Since no one else will develop.
I personally started helping photprism and wrote a RaspberryPi distro for them. I am not sure how to work with the current project unless its cleared up.
There is lots of unstable stuff on the UI side of things.

**Comment by JeongJuhyeon** [comment]
> Actually @lizyeseul has been touching the frontend a little he doesn't speak English or how to work with git AFIK
> see: [hooram/ownphotos-frontend#40](https://github.com/hooram/ownphotos-frontend/pull/40)

I could translate/explain if that'd help.

**Comment by shmuelpro** [comment]
Is there any update on this? 
I would love to take part on the front-end side of things

**Comment by guysoft** [comment]
Nothing new, still stuck. Only know that @hooram requested not to talk to anyone.

**Comment by sinc59** [comment]
Hello,
maybe we can fork the projet in the [new ownphotos](https://github.com/ownphotos) organization and made a list of 5 representative issue (frontend + backend + api).

This list might be the test of the new cooperation with volunters ?
I'm okay to contribute with my modest knowledge on django backend and docker.

Who wants to come ?

**Comment by NobleWolf** [comment]
> Hello,
> maybe we can fork the projet in the [new ownphotos](https://github.com/ownphotos) organization and made a list of 5 representative issue (frontend + backend + api).
> 
> This list might be the test of the new cooperation with volunters ?
> I'm okay to contribute with my modest knowledge on django backend and docker.
> 
> Who wants to come ?

I'm excited for this! Wish I had the skills to contribute.

**Comment by airfield20** [comment]
Hey guys, I'm interested in contributing new features to this project if allowed. I'm not well versed in Django or server management but I can help with image processing and AI features (photo rotation, resizing, cropping, face detection, object detection/annotation using YOLO, etc...). How do I help.

**Comment by phantomtypist** [comment]
@sinc59 @airfield20 @NobleWolf I'm going to make sure the most recent code is pulled to the new org and forked repos tonight.  I'll also pull over most, maybe all, the outstanding issues.

As far as "where to go from here" after that... I think I'll create a new issue in the repo and we can have some initial discussions and prioritize what we want to do.  If we want to do some informal chatting on Gitter we can do that too (I already set that up and I'll link to it in the future issue.)

**Comment by hialvaro** [comment]
Hey, Is this being continued finally? I see the new organization has no new activity. I really hope and wish this can be continued.

Maybe we could open a Matrix/IRC chat room to talk about this?

**Comment by ashishBharadwaj** [comment]
I would really like to contribute to this if its allowed? I think it's a great idea!

**Comment by airfield20** [comment]
@phantomtypist Looks like you cant add issues in forked repos. Should you copy the repo over instead of forking?

**Comment by eloo** [comment]
Hi guys,
as you might have seen i'm currently trying to setup up a travis pipeline for building and smoke testing the ownphotos backend.
I've also integrated dependabot for easy testing for version bumps.
Please feel free to use my changes for the new project 👍

**Comment by airfield20** [comment]
https://gitter.im/Ownphotos/community#

**Comment by kosciak9** [comment]
hello, is the fork progressing? would be happy to help out with frontend.

**Comment by hialvaro** [comment]
@kosciak9 Check out [Photoprism](photoprism.org)

**Comment by gpenland** [comment]
Hello, I'd like to help and move this project forward!

**Comment by derneuere** [comment]
Hey, I upgraded the dependencies for python 3.8 and was able to make a couple of small changes in the front and backend. If you find errors, just open an issue and I will try to fix it.

**Comment by MrColumbo** [comment]
thanks a lot @zainlol for creating a working docker file and all your support. Besides the mapbox stuff it seems to work fine so far for me. I will test the nextcloud stuff pretty soon since that is also a nice feature.

**Comment by Jogai** [comment]
Lets hope @hooram comes back, because he's active on github again: https://github.com/csiro-robotics/syropod_highlevel_controller/issues/6#issuecomment-689604945

**Comment by johan456789** [comment]
Since no one posts the link to the fork, here it is: https://github.com/LibrePhotos/librephotos

**Comment by guysoft** [comment]
@LibrePhotos @johan456789 @derneuere That finally looks like a decent fork with people working on it.

Should I put it on the top of the main page of OwnPhotos repo?
I could then close this issue and direct all traffic there.

**Comment by DigitalWarrior** [comment]
@guysoft Sounds like a prefect plan. Thank you.

**Comment by derneuere** [comment]
@guysoft That sounds like a great idea! 👍

**Comment by guysoft** [comment]
@derneuere Done, if you guys have any need for a pi docker/container build + a Pi distro ping me. Did also https://github.com/guysoft/PhotoPrismPi
