### ISSUE TITLE
Picture not having exif timestamp should also be displayed in the `Browse` page

### ISSUE THREAD

**Issue by arthurdk** [hooram/ownphotos-backend#14]
Picture not having exif timestamp should also be displayed in the `Browse` page.

It is currently not the case as the API filter photo not having a timestamp.

Two solutions : 

1. Return an `Unknown` album from the API containing those pictures
2. Set a default timestamp

What do you think of it? @hooram 

I'll probably implement it in a few days, but I'd like to have your opinion so my work won't go straight to the trash.

I hope PR are welcomed :)

**Comment by hooram** [comment]
I absolutely agree that this should be the case. I merged your PR that tries to parse the timestamp from the filename. Thanks for it. As for what to do with photos without a timestamp, I think option 1 would be a better choice. We can add a separate menu on the front end that lets you see photos without metadata.

**Comment by arthurdk** [comment]
Hey! Thanks for the 2 merges!

As for this issue. Do you mean a separate menu included in the main one or just another one directly on the Browse/AlbumByDays pages? I think the latter would be better in terms of user experience.

In terms of implement we can choose to make

1. the `date` field of the `AlbumDate` class nullable, which would be quite simple and allow to show the "Unknown" album on the frontend without any changes
2. Another API path for retrieving pics without metadata (unsure this is good idea honestly)


Anyway thanks for answering, I plan on contributing quite a lot on this project as I'm in a need of a Google Photos replacement and this seems to be a perfect fit. I'll add issues, features request and PR in the coming days.

**Comment by hooram** [comment]
Fixed
