### ISSUE TITLE
Nextcloud scan scans entire server / scan stuck at 75 photos

### ISSUE THREAD

**Issue by sysoppl** [hooram/ownphotos-backend#147]
This project seems to be dead, but latest PRs showed that there is some development going, so I'm creating this issue.

Using latest @zainlol docker image on fresh ubuntu 20.04 server, when I logged in and selected nextcloud folder to scan, after a while it showed photos from outside selected folder (generally it probably scan entire nextcloud server). 

Also, cpu usage drop after a while, and scan was stuck at 75 photos. 
None of photos in selected folder was shown.

**Comment by derneuere** [comment]
Hey @sysoppl 

I could reproduce your error, but it did not even want to scan one picture. Can you send me your logs?

**Comment by sysoppl** [comment]
So this time my Chrome shows blank page (even in incognito) with same error as in [here](https://github.com/hooram/ownphotos/pull/145#issuecomment-727616396), but Firefox works normally.
This time CPU usage drops when there was 89 scanned photos. I also tried to open one or two photos, with no success (infinity loading).
 
Here are the logs. I removed some IPs and changed nextcloud folder paths (selected folder is marked by "THIS_FOLDER_WAS_SELECTED").
[command_migrate.log](https://github.com/hooram/ownphotos/files/5561519/command_migrate.log)
[docker-compose.txt](https://github.com/hooram/ownphotos/files/5561520/docker-compose.txt)
[gunicorn_django.log](https://github.com/hooram/ownphotos/files/5561521/gunicorn_django.log)
[gunicorn_image_similarity.log](https://github.com/hooram/ownphotos/files/5561522/gunicorn_image_similarity.log)
[image_similarity.log](https://github.com/hooram/ownphotos/files/5561523/image_similarity.log)
[ownphotos.log](https://github.com/hooram/ownphotos/files/5561524/ownphotos.log)
[rqworker.log](https://github.com/hooram/ownphotos/files/5561525/rqworker.log)
[show_migrate.log](https://github.com/hooram/ownphotos/files/5561526/show_migrate.log)
[command_makemigrations.log](https://github.com/hooram/ownphotos/files/5561527/command_makemigrations.log)


It even shows 320 photos (there is ~70-100 in selected directory)
![image](https://user-images.githubusercontent.com/30871217/99560474-31298480-29c6-11eb-8bd0-03443159c430.png)

As always, fresh ubuntu 20.04 server





- - - - 
After restarting everything cpu usage is still idle, and scan seems to be still in progress
Photos however appear after a while

![image](https://user-images.githubusercontent.com/30871217/99563751-dd209f00-29c9-11eb-814f-747fd257c048.png)

![image](https://user-images.githubusercontent.com/30871217/99563811-f1fd3280-29c9-11eb-8b22-76199ea0ad16.png)
I can also open photos now

**Comment by derneuere** [comment]
@sysoppl I think I fixed the issues. The first issue was that the nextcloud job looked at the local scan path at not at the nextcloud scan path. The second issue was that delayed rq jobs silently crash. If a job instead is started immediately then it works. 

I pushed a new image. Please try it out and tell me if it fixed your issues.

**Comment by sysoppl** [comment]
It is fixed, thank you so much for your effort!
