### ISSUE TITLE
nextcloud scan is running forever

### ISSUE THREAD

**Issue by MrColumbo** [hooram/ownphotos-backend#149]
I added another "normal" user and added the nextcloud credentials. I was able to select a path on nextcloud and then click on nextcloud scan. When I login as admin and then go the admin portal I see scanning but no percentage and it is now more than 24 hours and there are only less than 20 photos in the directory I selected. 
Is there anything special I need to do?

**Comment by SchoofsEbert** [comment]
Looks like a duplicate of #147, did you try with the latest @zainlol version to see if that solves your issue?

Replace the image lines where it says `hooram/ownphotos*:dev` with `derneuere/ownphotos*:latest`

**Comment by MrColumbo** [comment]
I thought I already got the latest version but after recreating the images it works fine :+1:
