### ISSUE TITLE
Choose a directory from below not working in /admin

### ISSUE THREAD

**Issue by meyerdominik** [hooram/ownphotos-backend#151]
I can't give my user a directory. There are none to choose from.

I have the following in the Browser console:
> GET http://localhost/api/dirtree/ 500 (Internal Server Error)

and after that this:
> Warning: Each child in a list should have a unique "key" prop.
    Check the render method of `AdminPage`. See https://fb.me/react-warning-keys for more information.
      in TableRow (at AdminPage.js:168)
      in AdminPage (created by Connect(AdminPage))
      in Connect(AdminPage) (at privateRoute.js:31)
      in div (at privateRoute.js:30)
      in div (at privateRoute.js:29)
      in div (at privateRoute.js:28)
      in Route (at privateRoute.js:26)
      in PrivateRoute (created by Connect(PrivateRoute))
      in Connect(PrivateRoute) (at App.js:177)
      in Switch (at App.js:107)
      in div (at App.js:93)
      in Router (created by ConnectedRouter)
      in ConnectedRouter (at App.js:92)
      in App (created by Connect(App))
      in Connect(App) (at src/index.js:30)
      in CookiesProvider (at src/index.js:29)
      in Provider (at src/index.js:28)

The ownphotos.log just says:
> 2020-12-27 08:19:36,987 : views.py : get : 1603 : INFO : about to get root path tree
   2020-12-27 08:19:39,040 : views.py : get : 1605 : INFO : root path tree calculated

My `docker-compose.yml`:
> version: '2'

  services:
  
    proxy:
      image: guysoft/ownphotos-proxy
      tty: true
      container_name: ownphotos-proxy
      restart: always
      links:
        - "backend:backend"
        - "frontend:frontend"
      ports:
        - "80:80"
        
    ownphotos-db:
      image: postgres
      container_name: ownphotos-db
      restart: always
      environment:
      # This db password is internal, you can change it if you want, but also change it in ownphotos-backend container
        - POSTGRES_PASSWORD=AaAa1234
        - POSTGRES_DB=ownphotos
      volumes:
        - ownphotos-data:/var/lib/postgresql/data
  
    frontend:
      image: hooram/ownphotos-frontend:dev
      container_name: ownphotos-frontend
      #image: hooram/ownphotos-frontend:dev
      #build: ../ownphotos-frontend
      tty: true
      #volumes:
      #   - ../ownphotos-frontend/src:/usr/src/app/src
      environment:
         # This is the path to the backend host public facing. if your website is ownphotos.org then this should be "ownphotos.org".
         # Default here is assuming you are running on localhost on port 3000 as given in ownphotos-proxy service
         - BACKEND_HOST=localhost:80 # CHANGE ME IF YOU WANT
      links:
        - "backend:backend"
  
    backend:
      image: hooram/ownphotos:dev
      # For development uncomment this and comment the image name above
      #build: .
      container_name: ownphotos-backend
      volumes:
        - F://Google_Drive:/data/Google_Drive # CHANGE ME
        - E://ownphotos/storage/thumbnails:/code/protected_media # CHANGE ME
        - E://ownphotos/storage/logs:/code/logs # CHANGE ME
      environment:
        - SECRET_KEY=<secretkey> # CHANGE ME
        - BACKEND_HOST=backend # DON'T CHANGE ME
        - ADMIN_EMAIL=login@meyerdominik.de # CHANGE ME
        - ADMIN_USERNAME=meyerdominik # CHANGE ME
        - ADMIN_PASSWORD=<password> # CHAGNE ME
        - DEBUG=false
        - DB_BACKEND=postgresql
        - DB_NAME=ownphotos
        - DB_USER=postgres
        # This db password is internal, you can change it if you want, but also change it in ownphotos-db container
        - DB_PASS=AaAa1234
        - DB_HOST=ownphotos-db
        - DB_PORT=5432
        - REDIS_HOST=ownphotos-redis
        - REDIS_PORT=6379
        - MAPBOX_API_KEY=<apikey> # CHANGE ME - sign up at mapbox.com for an api key. You need this for reverse geocoding. 
      links:
        - "ownphotos-db:ownphotos-db"
        - "ownphotos-redis:ownphotos-redis"
    
    ownphotos-redis:
      image: redis
      container_name: ownphotos-redis
  
    volumes:
      ownphotos-data:
      media:

**Comment by derneuere** [comment]
Hey, ownphotos is no longer maintained. Here is a fork of ownphotos that is maintained: https://github.com/LibrePhotos/librephotos
If your issue still persists, please open a new issue in the librephotos repository.

**Comment by meyerdominik** [comment]
Thanks @derneuere !
