### ISSUE TITLE
Demo instance is offline

### ISSUE THREAD

**Issue by httpsterio** [hooram/ownphotos-backend#163]

**Comment by DigitalWarrior** [comment]
Ownphotos is no longer under active development. The repository was forked and is under active development at https://github.com/LibrePhotos/librephotos. For links to the demo visit the repo https://github.com/LibrePhotos/librephotos or the website https://librephotos.com

**Comment by httpsterio** [comment]
alright, thanks! I tried to look for probable forks but didn't see any successor to the project :)
