### ISSUE TITLE
Request - Package as a Nextcloud / Owncloud app

### ISSUE THREAD

**Issue by sunjam** [hooram/ownphotos-backend#19]
[Please consider packaging and releasing in the Nextcloud and Owncloud app store for easy deployment](https://nextcloudappstore.readthedocs.io/en/latest/developer.html). Thanks for all your good work!

**Comment by xXSTrikeXx** [comment]
Would love this feature in my Nextcloud 👍

**Comment by heviiguy** [comment]
Absolutely NOT. Nextcloud (oc) was was built on the premise of privacy and security. Unless the devs wish to sell out, the mere concept of facial recognition, which is utterly nefarious at its dark heart, should have no opportunity to spread its malicious tentacles into Nextcloud.

**Comment by sunjam** [comment]
Hmm, @arthurdk I think there is some FUD [regarding your CarDav PR request here.](https://github.com/hooram/ownphotos-backend/pull/18)  That is not actually a part of this existing software *yet*, but perhaps you could advise on any potential security concerns in regards to selfhosting.

**Comment by gruessung** [comment]
+1

**Comment by AlexHowser** [comment]
Is it also compatible to Nextcloud allredy?

**Comment by hooram** [comment]
I know there's some interest in this, but I won't work on it in any foreseeable future.

**Comment by petrk94** [comment]
@hooram 
well, we dont think you should to write a totally new plugin for NextCloud, I would like the integration TO Nextcloud. This would make it easier

**Comment by heviiguy** [comment]
GDPR. Be naive at your own risk: http://www.gdprarticles.com/gdpr-articles/data-subject-rights/does-gdpr-apply-to-photographs/
