### ISSUE TITLE
Make a page with screenshots and doc

### ISSUE THREAD

**Issue by rom1504** [hooram/ownphotos-backend#39]
Hi,
I installed ownphotos to see how it looked, and it's really amazing.
I've been looking into face recognition lately and was about to try to build something like ownphotos and it turns out you built almost exactly what I had in mind.

However, it's not obvious for people not used to github to find https://github.com/hooram/ownphotos/tree/master/screenshots

I think it would be great to have a page showing what ownphotos can do.

A public (limited) demo would be even better, but that requires an host, while a static page with screenshots could be hosted on github pages.

**Comment by P-a-t-r-i-c-k** [comment]
Hi,

Just wished to take a quick look and noticed the demo is not working at the moment. 
For me it returns:
`503 Service Temporarily Unavailable'

**Comment by hooram** [comment]
@P-a-t-r-i-c-k it's down. It was costing me quite a bit of money to run the demo site, so I took it down.

**Comment by rom1504** [comment]
I think having a simple static HTML page hosted on GitHub pages with screenshots would be a simple and free solution to this.

**Comment by guysoft** [comment]
@hooram Might be able to host it here, my connection is not super reliable, but its better than having a broken link as the first thing.

**Comment by hooram** [comment]
@guysoft @rom1504 I did quickly put together some screenshots of the latest commit on the dev branch and included them in readme. 

@guysoft, if you want to host it that would be awesome. Do you have some non-personal sample photos that you can use? A while back I downloaded the flickr dataset and gave them some fake metadata so that they will show on the map, etc. I could dig that up and share that with you if you'd like.

**Comment by rom1504** [comment]
Nice !

**Comment by guysoft** [comment]
Hey guys, 
I finally got ownphotos to boot and work. See PR: https://github.com/hooram/ownphotos-frontend/pull/31

I also have a **running instance** at: https://ownphotos.gnethomelinux.com/
User and default password are as the PR says: admin/admin.
The physical machine is at the [T.A.M.I makerspace](http://telavivmakers.org/).
I can't seem to get it to show images and would be great for help there.

Assuming the PR is merged, I can also add a [wachtower](https://github.com/v2tec/watchtower) which would automatically pull any change made in the github repo to the demo site automatically. And hope that would push this project to become updated and as awesome as its potential.

**Comment by guysoft** [comment]
Oh, got why there are no images, there is code commented out in dev:
https://github.com/hooram/ownphotos/blob/dev/api/directory_watcher.py#L32

I think @hooram commited it by unknowingly in this big commit: https://github.com/hooram/ownphotos/commit/c84abc420ffeb9e5c15de49ecee40beb8ccd56bd

This feature is broken for evreyone. I will see if I can get ownphotos-backend to build and PR, I think ubuntu upgraded to python 3.6 and this broke the pytorch installation.

**Comment by guysoft** [comment]
Ok, fixed it, its working on my server and is being built on docker hub as I type. @hooram Please pull, and sample photos would be great, I can find a photo or two of myself to share if it comes to that.

**Comment by petrk94** [comment]
@hooram I have tested the test instance of @guysoft and it looks very well, there are only small things I would maybe improve, the image loader when trying to open an image need longer time, and doesnt look so modern^^. But I would love to test the nextcloud image scan function. Does it works too with Nextcloud, if the files are connected over S3 storage?
Thanks

**Comment by guysoft** [comment]
@petrk94 I have several pull requests lined up to fix minor things, but first I want my current ones merged, so we can point all the ``docker-compose.yml`` to @hooram official build, and have something working, perhaps even release 0.2 in to master so we can start breaking dev again fixing all the small things.

But I am ahead of myself, @hooram needs to answer first.

**Comment by guysoft** [comment]
Yay @hooram merged!

The only thing that is left for my fork to be fully in sync is for @hooram to create a docker.hub automated build for ownphotos-frontend container.
Similar to the one I set up here:
https://cloud.docker.com/u/guysoft/repository/docker/guysoft/ownphotos-frontend

Also mentioned here: https://github.com/hooram/ownpahotos-frontend/pull/31#issuecomment-448193722

@hooram If you want help with that ping me.

Then I can PR that the ``docker-compose.yml`` will point to hooram's docker hub images.

**Comment by guysoft** [comment]
Ok, now that I can push stuff here the plan is to add the demo site in to the readme and close this issue, unless anyone wants anything else added.
