### ISSUE TITLE
Docker images for front-end and back-end should be built separately

### ISSUE THREAD

**Issue by depau** [hooram/ownphotos-backend#41]
The current Dockerfile (and the one I updated with #40) build an image that contains both the front-end and the back-end.

It might be a better practice to build them separately, and using Docker Compose to orchestrate all the containers and run everything automatically.

Also, I noticed that the entry point builds JS stuff on startup. I think it might be better if it were built at image build time, as unless changes are placed in a volume, they're lost when the container is stopped/restarted.

**Comment by guysoft** [comment]
This is starting to happen, see this setup:
https://github.com/hooram/ownphotos-frontend/blob/dev/docker-compose.yml#L27

The only thing that is left is to remove the frontend form the Dockerfile and then image would be much lighter!

**Comment by guysoft** [comment]
This is also part of PR #46
