### ISSUE TITLE
ownphotos-backend is unavailable during `docker-compose up`

### ISSUE THREAD

**Issue by danielhoherd** [hooram/ownphotos-backend#47]
# Symptom

Unable to complete `docker-compose up`:

```
Pulling backend (ownphotos-backend:)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling backend (ownphotos-backend:)...
ERROR: pull access denied for ownphotos-backend, repository does not exist or may require 'docker login'
```

# Steps to reproduce:

```
git clone git@github.com:hooram/ownphotos.git
cd ownphotos
docker-compose up
```

# More info

- Related line in docker-compose.yml: https://github.com/hooram/ownphotos/blob/e1285a795a6753f5bef396ffe32c8b65e1b3ad70/docker-compose.yml#L11

**Comment by guysoft** [comment]
Ok two things
1. You didnt log in to docker hub, you need to run ``docker login``
2. Its recommended, once you logged in, to use this instruction, it will use images built already and you will not to build them yourself:
https://github.com/hooram/ownphotos-frontend/issues/8#issuecomment-447003146

**Comment by guysoft** [comment]
Closing if no reply.

**Comment by danielhoherd** [comment]
I think that 5b5e8790094a722126e81ff0cba02946616b1303 addresses this report so I'm closing it. Thanks for the quick reply!
