### ISSUE TITLE
When docker container upgraded, ownphotos doesn't use existing admin user

### ISSUE THREAD

**Issue by gregbert42** [hooram/ownphotos-backend#50]
Instead, it marks the existing admin user as 'deleted' and creates a new admin user, who does not inherit the photos previously uploaded. and i cannot access the photos that were part of the previous 'admin' user (not 'deleted')

![image](https://user-images.githubusercontent.com/16961761/50490877-b7720180-0a0f-11e9-8e6c-47e21b0e8777.png)

**Comment by guysoft** [comment]
That is strange, I've been upgrading all the time and it seemed to have work. But I might have deleted the volume.
If you don't have any data appended there for now you could just delete the db volume.

```
docker-compose stop
docker-compose rm 
docker volume rm ownphotos_ownphotos-data
docker-compose up -d
```

**Comment by gregbert42** [comment]
yes, ive deleted everything now in order to start with a completely fresh version so i can send you good logs for the other issue.

But requires rescanning the photos (or a direct edit to DB).

**Comment by hooram** [comment]
Maybe it's from line 16 on entrypoint.sh?

**Comment by guysoft** [comment]
You can link to a line like this: https://github.com/hooram/ownphotos/blob/dev/entrypoint.sh#L16

Yes, that looks like it.
Perhaps something along this line is better?:

I am not sure if len works in this context.
I don't know how to implement update_password and can't see an example in the code.

```
if len(User.objects.filter(email='$ADMIN_EMAIL')) > 0:
    update_password(User.objects.filter(email='$ADMIN_EMAIL'), '$ADMIN_EMAIL', '$ADMIN_PASSWORD')
else:
    User.objects.create_superuser('$ADMIN_USERNAME', '$ADMIN_EMAIL', '$ADMIN_PASSWORD')
```

I would appriicate pointers on how to do that.

**Comment by hooram** [comment]
Closing. see https://github.com/hooram/ownphotos/commit/66927b16e03590928cba067e103d4e63c3abe9ca
