### ISSUE TITLE
Backend won't boot

### ISSUE THREAD

**Issue by jwolansk** [hooram/ownphotos-backend#58]
Hello, I'm trying to install using docker-compose
> wget https://raw.githubusercontent.com/hooram/ownphotos/dev/docker-compose.yml
> docker-compose up -d

The backend cannot boot with the logs:

[backend.log](https://github.com/hooram/ownphotos/files/2768330/backend.log)

Isn't it related to an old numpy version?

**Comment by hooram** [comment]
Can you try `docker pull hooram/ownphotos:dev` and `docker-compose up -d` again? It looks like you're not running the latest image.

**Comment by jwolansk** [comment]
I've updated the image, the backend boots. With my first try, the yesterdays image was downloaded I did that few minutes before a new one was available 🙂 
Thanks!
