### ISSUE TITLE
Possibly hanging worker?

### ISSUE THREAD

**Issue by wtrdk** [hooram/ownphotos-backend#67]
Last night I installed OwnPhotos (my compliments for your very cool app!). It could'nt connect to the backend. While trying to login I got this message:
 
"No connection to backend server"

I left the instance running overnight, and just checked the logs:
A lot of 'Sent heartbeat' messages, and at the moment I tried to login again I got the 'Not found' message.
```
07:14:58 Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.
07:21:43 Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.
07:28:28 Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.
07:35:13 Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.
07:41:58 Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.
Not Found: /robots.txt
```
As mentioned in https://github.com/hooram/ownphotos/issues/52#issuecomment-460576955 I report this as a new issue

**Comment by guysoft** [comment]
Just to make sure - are you on the latest container with a clean db? Because I had this issue, but latest hooram/ownphotos seems to fix it for me.

Also what is the output of http://localhost:3000/api/ ?

**Comment by wtrdk** [comment]
> Just to make sure - are you on the latest container with a clean db? Because I had this issue, but latest hooram/ownphotos seems to fix it for me.
> 
> Also what is the output of http://localhost:3000/api/ ?

Hi, as far as I know I am using the latest container. I deployed it last night...
The output of http://localhost:3000/api/ is a lot of text, I put it in a .txt file and added it as an attachment to keep this thread clean ;-)

[api.txt](https://github.com/hooram/ownphotos/files/2832440/api.txt)

**Comment by guysoft** [comment]
Ok, that otuput is what you expect, it says "I can't find /api", but here are a list of all the paths that work.
This means your backend server is working.
@hooram Perhaps there is a command we can send to the backend to kill and start the worker or get a log or response or something?

**Comment by wtrdk** [comment]
I stopped the backend and brought it back up again several times, but that didn't solve the problem.
More logging:
```
19:36:08 Registering birth of worker 9330aab10489.77
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/miniconda/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/miniconda/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/miniconda/lib/python3.7/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/miniconda/lib/python3.7/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/miniconda/lib/python3.7/site-packages/django_rq/management/commands/rqworker.py", line 100, in handle
    w.work(burst=options.get('burst', False))
  File "/miniconda/lib/python3.7/site-packages/rq/worker.py", line 466, in work
    self.register_birth()
  File "/miniconda/lib/python3.7/site-packages/rq/worker.py", line 276, in register_birth
    raise ValueError(msg.format(self.name))
ValueError: There exists an active worker named '9330aab10489.77' already

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```
And after trying top open http://localhost:3000/api : 
```
Not Found: /api
```

Please let me know if there's something I can try or do to help out! (and your quick response is awesome 👍 )

**Comment by wtrdk** [comment]
Hi, no update yet? I'm just so eager to use this software ;-)

**Comment by guysoft** [comment]
the current log does not help pin point the issue.

You could try flushing all the containers and volumes.
Also @hooram said something about ``/media_protected`` might be related to
that.

**Comment by wtrdk** [comment]
I'm very sorry and ashamed of myself... I found out I didn't adjust the localhost setting in the docker-compose.yml file. After adjusting that everything worked fine!
Very sorry to bother you! :-(

**Comment by guysoft** [comment]
No shame in reporting issues and how you solved them, wish more would.



![wisdom_of_the_ancients](https://user-images.githubusercontent.com/325670/52572299-308eb200-2e20-11e9-9cc4-debfff03ba18.png)
