### ISSUE TITLE
Difference of signing into Nextcloud or Scanning the directory directly

### ISSUE THREAD

**Issue by coxtor** [hooram/ownphotos-backend#95]
Hello, just for clarity:
Are there any disadvantages or benefits in connecting to Nextcloud via the web-ui, over using the mounted Nextcloud directory directly on the HDD, when Nextcloud and Ownphotos are running on the same host?

Important questions here are:

- Does Ownphotos ever intend to modify the scan directory? 
- How big is the overhead caused when connecting to Nextcloud, as the images need to be transferred via the network to be processed by Ownphotos?

Thank you for clarifying.

**Comment by hooram** [comment]
If they live on the same machine, 100% use the mounted nextcloud directory. If you connect to a nextcloud account through the web UI, the ownphotos instance will make copies of photos in the nextcloud account, which is unnecessary on the same machine. It does not modify the scan directory.
